tunnel: b0c1ce2b-d362-4644-82a6-d24bb512c1bf
credentials-file: /etc/cloudflared/tunnel.json
protocol: http2
metrics: 0.0.0.0:2000
ingress:
  - hostname: tickets.yama.asia
    service: http://web:80
  - service: http_status:404
